# Generated by Django 4.1.7 on 2023-05-01 12:46

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("username", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=150)),
                ("phone", models.IntegerField()),
                ("address", models.CharField(max_length=150)),
                ("ville", models.CharField(max_length=50)),
                ("postal", models.IntegerField()),
                ("country", django_countries.fields.CountryField(max_length=2)),
            ],
            options={
                "verbose_name": "profile",
                "verbose_name_plural": "Profiles",
                "db_table": "Profile",
            },
        ),
    ]
