# Generated by Django 4.1.7 on 2023-05-01 23:38

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("utilisateur", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="profile",
            managers=[("objects", django.contrib.auth.models.UserManager()),],
        ),
        migrations.RenameField(
            model_name="profile", old_name="ville", new_name="city",
        ),
        migrations.RemoveField(model_name="profile", name="email",),
        migrations.RemoveField(model_name="profile", name="id",),
        migrations.RemoveField(model_name="profile", name="username",),
        migrations.AddField(
            model_name="profile",
            name="user_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
