# Generated by Django 4.2 on 2023-04-29 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voiture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=250)),
                ('couleurs', models.CharField(default='', max_length=250)),
                ('prix_moyen', models.CharField(default='', max_length=250)),
                ('consommation_carburant', models.CharField(default='', max_length=250)),
                ('technologie_securite', models.CharField(default='', max_length=250)),
                ('confort_de_conduite', models.CharField(default='', max_length=250)),
                ('espace_intérieur', models.CharField(default='', max_length=250)),
                ('connectivité', models.CharField(default='', max_length=250)),
                ('image', models.ImageField(upload_to='static/img_base')),
            ],
            options={
                'verbose_name': 'voiture',
                'verbose_name_plural': 'Voitures',
                'db_table': 'Voiture',
            },
        ),
    ]
