# Generated by Django 4.2 on 2023-04-29 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='postal',
            field=models.IntegerField(),
        ),
    ]
