# Generated by Django 4.1.7 on 2023-05-01 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0003_alter_profile_phone_alter_profile_postal"),
    ]

    operations = [
        migrations.DeleteModel(name="Profile",),
    ]
